version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    restart: always
    ports:
      - '8123:8123'
      - '9000:9000'

  scraper:
    env_file:
      - .env
    build: .
    depends_on:
      - clickhouse
    command: /bin/bash -c "python -u app/scraper.py"

  reporter:
    env_file:
      - .env
    build: .
    depends_on:
      - clickhouse
    ports:
      - '5000:5000'
    command: /bin/bash -c "python -u app/reporter.py"